name: Get version
description: ""
outputs:
  version:
    description: Version
    value: ${{ steps.version.outputs.targetVersion }}
  isPrerelease:
    description: Is Prerelease
    value: ${{ steps.version.outputs.targetIsPrerelease }}
  isLatest:
    description: Is latest version in repository
    value: ${{ steps.version.outputs.isLatestVersion }}
  isHighest:
    description: Is highest version in repository
    value: ${{ steps.version.outputs.isHighestVersion }}
  major:
    description: Major version
    value: ${{ steps.version.outputs.targetMajor }}
  minor:
    description: Minor version
    value: ${{ steps.version.outputs.targetMinor }}
  patch:
    description: Patch version
    value: ${{ steps.version.outputs.targetPatch }}
  latestVersion:
    description: Latest version in repository
    value: ${{ steps.version.outputs.latestVersion }}
  highestVersion:
    description: Highest version in repository
    value: ${{ steps.version.outputs.highestVersion }}

runs:
  using: composite
  steps:
    - id: version
      name: Check Version
      uses: cpdevtools/action-versions@main