name: Setup Node
description: Setup node, pnpm and install dependencies
inputs:
  pnpmVersion:
    description: The version of pnpm to install
    required: false
    default: 7.26.2
  nodeVersion:
    description: The version of NodeJs to install
    required: false
    default: 16.18.1
  githubToken:
    description: Github Token
    required: false
    default: ${{ github.token }}
  runInstall:
    description: Run install
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpmVersion }}
        run_install: false

    - uses: actions/setup-node@v3.6.0
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - run: pnpm install --ignore-scripts --frozen-lockfile
      if: ${{ inputs.runInstall == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
