name: Create Release Pull Request
description: Create Pull Request if required

inputs:
  githubToken:
    description: Github Token
    required: false
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Auto Create
      uses: cpdevtools/action-versions@v0.5
      with:
        autoCreatePullRequest: true