name: Create Nuget Packages
description: Create nuget packages

inputs:
  version:
    description: "The version of the library"
    required: true
  dotnetVersion:
    description: "The version of .net to install"
    required: false
    default: "5.x"
  pnpmVersion:
    description: The version of pnpm to install
    required: false
    default: 7.26.2
  nodeVersion:
    description: The version of NodeJs to install
    required: false
    default: 16.18.1


runs:
  using: composite
  steps:
    - name: Install Node & Dependencies
      uses: cpdevtools/github-workflows/.github/actions/common/node-setup-pnpm@main
      with:
        pnpmVersion: "${{ inputs.pnpmVersion }}"
        nodeVersion: "${{ inputs.nodeVersion }}"

    - name: Install .NET
      uses: cpdevtools/github-workflows/.github/actions/common/dotnet-setup@main
      with:
        dotnetVersion: "${{ inputs.dotnetVersion }}"

    - name: Set dotnet versions
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ inputs.version }}

    - name: Build
      run: pnpm run actions-build
      shell: bash

    - name: Package
      run: pnpm run actions-package
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        if-no-files-found: error
        path: |
          **/*.nupkg
          **/*.snupkg