name: Push

on:
  push:
    branches:
      - "main"
      - "master"
      - "v/*"

jobs:
  create-release-pr:
    name: Create Pull Request
    uses: cpdevtools/github-workflows/.github/workflows/create-release-pull-request.yml@main