name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - "release/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      isPrerelease: ${{ steps.version.outputs.isPrerelease }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
        
      - name: Check Version
        id: version
        uses: cpdevtools/github-workflows/.github/actions/common/check-version@main

  publish:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.TEMPLATE_TOKEN }}

      - uses: fregante/setup-git-user@v2

      - name: Install Node & Dependencies
        uses: cpdevtools/github-workflows/.github/actions/common/node-setup-pnpm@main

      - name: Create release branch
        run: pnpm run actions-release --version=${{ needs.setup.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Create Release
        id: create_release
        uses: cpdevtools/github-workflows/.github/actions/common/create-release@main

      # fixes an issue with the external actions/workflows not being able to create/publish a release that is not draft
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.releaseId }}
